[build]
builder = "nixpacks"

[build.builders.nixpacks]
buildCommand = "dotnet restore Tracker/TrackerBackend/TrackerBackend.csproj && dotnet publish tracker/TrackerBackend/TrackerBackend.csproj -c Release -o out"

[deploy]
startCommand = "dotnet out/TrackerBackend.dll"
