//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class directions
    {
        public directions()
        {
            this.groups = new HashSet<groups>();
        }
    
        public int direction_id { get; set; }
        public int faculty_id { get; set; }
        public string name { get; set; }
    
        public virtual faculty faculty { get; set; }
        public virtual ICollection<groups> groups { get; set; }
    }
}
