//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class journal
    {
        public int journal_id { get; set; }
        public int schedule_id { get; set; }
        public int student_id { get; set; }
        public System.DateTime lesson_date { get; set; }
        public Nullable<int> grade { get; set; }
        public string attendance { get; set; }
    
        public virtual schedule schedule { get; set; }
        public virtual users users { get; set; }
    }
}
