//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class lesson_times
    {
        public lesson_times()
        {
            this.schedule = new HashSet<schedule>();
        }
    
        public int time_slot_id { get; set; }
        public int lesson_number { get; set; }
        public System.TimeSpan time_start { get; set; }
        public System.TimeSpan time_end { get; set; }
    
        public virtual ICollection<schedule> schedule { get; set; }
    }
}
