//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class news
    {
        public int news_id { get; set; }
        public int user_id { get; set; }
        public string news_title { get; set; }
        public string news_text { get; set; }
        public System.DateTime publication_date { get; set; }
    
        public virtual users users { get; set; }
    }
}
