//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule
    {
        public schedule()
        {
            this.journal = new HashSet<journal>();
        }
    
        public int schedule_id { get; set; }
        public int group_id { get; set; }
        public int subject_id { get; set; }
        public int teacher_id { get; set; }
        public int classroom_id { get; set; }
        public string day_of_week { get; set; }
        public int time_slot_id { get; set; }
        public string week_type { get; set; }
        public int description_id { get; set; }
    
        public virtual classrooms classrooms { get; set; }
        public virtual descriptions descriptions { get; set; }
        public virtual groups groups { get; set; }
        public virtual ICollection<journal> journal { get; set; }
        public virtual lesson_times lesson_times { get; set; }
        public virtual subjects subjects { get; set; }
        public virtual users users { get; set; }
    }
}
