//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class subjects
    {
        public subjects()
        {
            this.schedule = new HashSet<schedule>();
            this.users = new HashSet<users>();
        }
    
        public int subject_id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<schedule> schedule { get; set; }
        public virtual ICollection<users> users { get; set; }
    }
}
