//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.journal = new HashSet<journal>();
            this.news = new HashSet<news>();
            this.schedule = new HashSet<schedule>();
            this.subjects = new HashSet<subjects>();
        }
    
        public int user_id { get; set; }
        public string fio { get; set; }
        public int role_id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
    
        public virtual ICollection<journal> journal { get; set; }
        public virtual ICollection<news> news { get; set; }
        public virtual roles roles { get; set; }
        public virtual ICollection<schedule> schedule { get; set; }
        public virtual groups groups { get; set; }
        public virtual ICollection<subjects> subjects { get; set; }
    }
}
